server:
  port: 1010


spring:
  application:
    name: PRODUCT-SERVICE
  data:
    mongodb:
      uri:

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka